{% set name = "jiwer" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jiwer-{{ version }}.tar.gz
  sha256: bb7417f1f8e4466259bf53736a1dacdf399b409c25c42bbc0958e482c4e2c261

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.7,<4.0
    - rapidfuzz >=2.13.7
    - click >=8.1.3

test:
  imports:
    - jiwer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jitsi/jiwer
  summary: Evaluate your speech-to-text system with similarity measures such as word error rate (WER)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
