{% set name = "jiwer" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jiwer-{{ version }}.tar.gz
  sha256: a777f361a5a5f76012078d758e444e1da2a171fb685dad9cf8fb69181ea26ee6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.7,<4.0
    - rapidfuzz >=3.0.0,<4.0.0
    - click >=8.1.3,<9.0.0

test:
  imports:
    - jiwer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jitsi/jiwer
  summary: Evaluate your speech-to-text system with similarity measures such as word error rate (WER)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
